name: deploy

on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types:
      - completed

permissions:
  contents: write

jobs:
  tagging:
    runs-on: ubuntu-latest

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        fetch-tags: true
        fetch-depth: 0

    - name: Get tag from commit (if any)
      if: "contains(github.event.head_commit.message, 'dump: v')"
      run: |
        COMMIT_TAG="${{ github.event.head_commit.message }}"
        COMMIT_TAG=$(echo "$COMMIT_TAG" | cut -d' ' -f2)
        echo "COMMIT_TAG=$COMMIT_TAG" >> $GITHUB_ENV

    - name: Generate Git Tag
      id: generate_tag
      run: |
        if [ -n "$COMMIT_TAG" ]; then
          NEW_TAG=$COMMIT_TAG
        else
          latest_tag="$(git tag --list "v*" --sort=-version:refname | head -n 1)"
          echo $latest_tag
          [ -z "$latest_tag" ] && latest_tag=v0.0.0

          major_minor=$(echo "$latest_tag" | cut -d'.' -f-2)
          patch=$(echo "$latest_tag" | cut -d'.' -f3)
          patch=$(( $patch + 1 ))

          NEW_TAG="${major_minor}.${patch}"
        fi

        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Push Git Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git tag $NEW_TAG
        git push origin $NEW_TAG
