name: deploy

on:
  workflow_run:
    workflows: [test]
    branches: [main]
    types:
      - completed

permissions:
  contents: write

jobs:
  tagging:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
    - name: Clone the repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get tag from commit (if any)
      if: "contains(github.event.workflow_run.head_commit.message, 'dump: v')"
      run: |
        COMMIT_TAG="${{ github.event.workflow_run.head_commit.message }}"
        COMMIT_TAG=$(echo "$COMMIT_TAG" | cut -d' ' -f2)
        echo "COMMIT_TAG=$COMMIT_TAG" >> $GITHUB_ENV

    - name: Generate Git Tag
      id: generate_tag
      run: |
        if [ -n "$COMMIT_TAG" ]; then
          NEW_TAG=$COMMIT_TAG
        else
          latest_tag="$(git tag --list "v*" --sort=-version:refname | head -n 1)"
          echo $latest_tag
          [ -z "$latest_tag" ] && latest_tag=v0.0.0

          major_minor=$(echo "$latest_tag" | cut -d'.' -f-2)
          patch=$(echo "$latest_tag" | cut -d'.' -f3)
          patch=$(( $patch + 1 ))

          NEW_TAG="${major_minor}.${patch}"
        fi

        echo "Generated new tag: $NEW_TAG"
        echo "NEW_TAG=$NEW_TAG" >> $GITHUB_ENV

    - name: Generate changelog
      id: generate_changelog
      run: |
        latest_tag="$(git tag --list "v*" --sort=-version:refname | head -n 1)"
        changelog=$(git log $latest_tag..HEAD --pretty=format:"- %s")
        echo "Changelog between $latest_tag and $NEW_TAG:"
        echo "$changelog"
        {
          echo 'CHANGELOG<<EOF'
          echo "$changelog"
          echo 'EOF'
        } >> $GITHUB_ENV

    - name: Push Git Tag
      run: |
        git config user.name "GitHub Actions"
        git config user.email "github-actions@users.noreply.github.com"
        git tag -a $NEW_TAG -m "New version $NEW_TAG"$'\n\n'"Changes:"$'\n'"$CHANGELOG"
        git push origin $NEW_TAG
